### ISSUE TITLE
ssh_key input question 

### ISSUE THREAD

**Issue by asaf-upstream** [3h4x/terragrunt-github-actions#6]
Hi!
Would appreciate your support with the feature you've added. 
I am trying to use the `ssh_key` input like this:

```
      - name: 'Terragrunt Plan'
        uses: 3h4x/terragrunt-github-actions@master
        with:
          ssh_key: ${{ secrets.TF_REPO_SSH_PRIVATE_KEY }}
          tf_actions_version: ${{ env.tf_version }}
          tg_actions_version: ${{ env.tg_version }}
          tf_actions_binary: "terragrunt run-all"
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
```

However, i am getting 

```
time=2023-05-31T12:34:30Z level=error msg=Module /github/**/s3_bucket has finished with an error: 1 error occurred:
	* error downloading 'ssh://git@github.com/**.git?ref=master': /usr/bin/git exited with 128: fatal: could not create leading directories of '/github/workspace/aws/**/.terragrunt-cache/i3ZAWR8kCy4HmStWmVGC0JUeigM/crZTLJHL1I3LbHHwLtXIVMEldJk': Permission denied
```
On all the submodules dirs..

I will mention that I have 2 previous steps that imports the pem and cloning the repo successfully with same key: 

```
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.TF_REPO_SSH_PRIVATE_KEY }}
      
      - name: test - regular ssh
        run: | 
          git clone ssh://git@github.com/**.git terraform
```

Anything I miss with the usage?
